import type { Metadata } from "next";
import localFont from "next/font/local"
import { Geist, Geist_Mono, Besley} from "next/font/google";
import "./globals.css";

const blackChancery = localFont({
  src: './fonts/BLKCHCRY.ttf',
  variable: '--font-blackChancery',
})

const besley = Besley({
  variable: "--font-besley",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
